version: '3'

services:

  database:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_HOST: 'localhost'
      MYSQL_DATABASE: 'todolist'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''

    ports:
      - "3306:3306"

  backend:
    container_name: backend
    depends_on:
      - database
    build: 
      context: ../backend

    environment:
      MYSQL_HOST: 'localhost'
      MYSQL_DATABASE: 'todolist'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''

    ports:
      - "3000:3000"
      

  frontend:
    container_name: frontend
    build: 
      context: ../frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

